### ISSUE TITLE
Background color of Tile is not getting darkened by open SideNav

### ISSUE THREAD

**Issue by Florian-Schoenherr** [carbon-design-system/carbon-components-svelte#786] opened 2021-08-11 13:00 UTC
![image](https://user-images.githubusercontent.com/65456722/129031968-5f3caeca-38ec-4d3f-a401-a6610e42e130.png)

Repro: https://svelte.dev/repl/62ceeb8d704d44f09d255b2bd58d68ec?version=3.42.1

**Comment by Florian-Schoenherr** [comment] 2021-08-11 13:09
SideNav has a z-index of 8000, right?
I don't know much about the code so I can only recommend something like z-index 5000 for the overlay.

**Comment by deviumgroup** [comment] 2022-02-25 02:14
How is it going with this one, any solution? I dont want to put the navbar inside the header.

**Comment by CicadaCinema** [comment] 2022-04-27 14:12
Looks like this may be fixed now?
![NVIDIA_Share_2007](https://user-images.githubusercontent.com/52425971/165538529-7e835692-f40e-4233-9dca-b3b649da15f3.gif)

**Comment by metonym** [comment] 2022-04-30 16:19
> Looks like this may be fixed now?

Yep, seems to work now in both the REPL as well as locally.

**Comment by slavnycoder** [comment] 2022-07-12 15:38
Still reproducing. https://pastebin.com/sUxU1aS5  

![image](https://user-images.githubusercontent.com/13649915/178530050-16d3e835-31f1-41a3-bd9d-11b9a99c2ec6.png)

**Closed** 2022-07-13 02:43 UTC
Labels: bug

**Comment by metonym** [comment] 2022-07-13 02:49
Fixed in [v0.67.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.67.1)
