### ISSUE TITLE
HeaderNav not rendering on mobile devices

### ISSUE THREAD

**Issue by chipnetics** [carbon-design-system/carbon-components-svelte#1673] opened 2023-02-28 20:43 UTC
Visiting the UIShell example [here](https://carbon-components-svelte.onrender.com/framed/UIShell/Header?theme=white) (which is the very first example in the [docs](https://carbon-components-svelte.onrender.com/components/UIShell) when you click "Open in new tab"), renders fine in desktop browsers; however the menu items do not appear on android chrome mobile.  And oddly.. they don't seem to appear within the iframe example either on the desktop on the docs page. 🤷

Hope this is clear! Thanks

**Comment by brunnerh** [comment] 2023-02-28 21:03
Probably a duplicate of:
- https://github.com/carbon-design-system/carbon-components-svelte/issues/516

**Comment by theetrain** [comment] 2023-03-01 02:39
I appreciate the call-out; as we progress towards adopting v11 styles, we'll try to resolve all open UIShell issues as well.

- #1674 (includes your reported issue)

Closing this as a duplicate of #516.

**Closed by theetrain** 2023-03-01 02:39 UTC
