### ISSUE TITLE
Pagination component with lots of pages has massive render time

### ISSUE THREAD

**Issue by jhwz** [carbon-design-system/carbon-components-svelte#1340] opened 2022-06-08 22:31 UTC
When you have a pagination component with a large value set for totalItems, the page takes ages to render because of the page Select element, more specifically this loop:

```svelte
        {#each selectItems as size, i (size)}
          <SelectItem value="{size + 1}" text="{(size + 1).toString()}" />
        {/each}
```

It's not hard to check for this and set `pageInputDisabled` if the number of pages exceeds a threshold. I just wanted to bring the issue to attention if it wasn't already known about. Took me a minute to figure out why my page all of sudden broke!

**Comment by metonym** [comment] 2022-06-09 01:15
This does seem to be a known issue that also affects the React and Vue implementations. I'm able to reproduce the crash when I specify over 100k total items in a `Pagination`. 

https://github.com/carbon-design-system/carbon/issues/6905
https://github.com/carbon-design-system/carbon/issues/4365
https://github.com/carbon-design-system/carbon-components-vue/issues/831
https://github.com/carbon-design-system/carbon/issues/6905
https://github.com/carbon-design-system/carbon/issues/9754

This is the best answer I've seen: https://github.com/carbon-design-system/carbon/issues/9754#issuecomment-928200962

**Comment by jhwz** [comment] 2022-06-09 01:24
Yeap that's what I've resorted to, disabling the page input when I have more than 1K pages. Shame to have to do that!

I'm happy for this issue to be closed if you see it as an upstream issue :)

**Comment by metonym** [comment] 2022-06-09 01:41
Oh interesting, apparently from [this comment](https://github.com/carbon-design-system/carbon-components-vue/issues/831#issuecomment-590403862), Chrome and other browsers actually limit the number of rendered [`select` elements to 10,000](https://chromium.googlesource.com/chromium/blink.git/+/master/Source/core/html/HTMLSelectElement.cpp#77).

I'm going to close this as this seems to be a browser limitation that is not language or library specific. The only way is to workaround from a design standpoint, like what you mentioned.

**Closed by metonym** 2022-06-09 01:41 UTC
